import Head from "next/head";
import { FaExternalLinkAlt } from "react-icons/fa";

import Layout from "@components/Layout";
import Container from "@components/Container";

import styles from "@styles/Page.module.scss";
import { STORES_QUERY } from "@utils/queries";
import { setClientAndGetData } from "@utils/commonScripts";
import AppMapDynamic from "@components/AppMap";

export default function Stores({ storeLocations }) {
  // console.log(`Stores.js => storeLocations: ${storeLocations}`);

  return (
    <Layout>
      <Head>
        <title>Store Locations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Locations</h1>

        <div className={styles.stores}>
          <div className={styles.storesLocations}>
            <ul className={styles.locations}>
              {storeLocations.map((location) => (
                <li key={location.id}>
                  <p className={styles.locationName}>{location.name}</p>

                  <address>{location.address}</address>

                  <p>{location.phoneNumber}</p>
                  <p className={styles.locationDiscovery}>
                    <button>View on Map</button>
                    <a
                      href={`https://www.google.com/maps/dir//${location.location.latitude},${location.location.longitude}/@${location.location.latitude},${location.location.longitude},16z`}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Get Directions
                      <FaExternalLinkAlt />
                    </a>
                  </p>
                </li>
              ))}
            </ul>
          </div>

          <div className={styles.storesMap}>
            <div className={styles.storesMapContainer}>
              <AppMapDynamic className={styles.map}>
                {({ TileLayer, Marker, Popup }, map) => {
                  const position = [51.505, -0.09];

                  return (
                    <>
                      <TileLayer
                        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                      />
                      <Marker position={position}>
                        <Popup>
                          A pretty CSS3 popup. <br /> Easily customizable.
                        </Popup>
                      </Marker>
                    </>
                  );
                }}
              </AppMapDynamic>
            </div>
          </div>
        </div>
      </Container>
    </Layout>
  );
}

export async function getStaticProps() {
  const queryResult = await setClientAndGetData(STORES_QUERY);

  return {
    props: {
      storeLocations: queryResult.data.storeLocations,
    },
  };
}
